spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?serverTimezone=UTC
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: create # hibernate will validate the schema
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true # in order to see sql query from our console in dev