spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod?serverTimezone=UTC
    username: sfg_prod_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate # hibernate will validate the schema
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false # we don't want to see query in console in prod